all:
  children:
    monitoring:
      hosts:
        grafana:
          ansible_host: master
          ansible_user: ubuntu
    nodes:
      hosts:
        worker-1:
          ansible_host: worker-1
          ansible_user: ubuntu
        worker-2:
          ansible_host: worker-2
          ansible_user: ubuntu
        worker-3:
          ansible_host: worker-3
          ansible_user: ubuntu
